// data/portfolioData.js
export const portfolios = [
  {
    id: "pavilion-hostel",
    name: "The Pavilion Hostel",
    location: "University District, Zone A",
    type: "Hostel",
    status: "Active",
    image: "/assets/image 1.png",
    occupancy: "92%",
    totalUnits: 50,
    roi: "12.5%",
    valuation: "$1.2M",
  },
    {
    id: "hinansho-residence-one",
    name: "Hinansho Residence One",
    location: "University District, Zone A",
    type: "Hostel",
    status: "Active",
    image: "/assets/image 2.png",
    occupancy: "92%",
    totalUnits: 50,
    roi: "12.5%",
    valuation: "$1.2M",
  },
    {
    id: "hinansho-residence-two",
    name: "Hinansho Residence Two",
    location: "University District, Zone A",
    type: "Hostel",
    status: "Active",
    image: "/assets/image 3.png",
    occupancy: "92%",
    totalUnits: 50,
    roi: "12.5%",
    valuation: "$1.2M",
  },
  {
        id: "hinansho-residence-three",
    name: "Hinansho Residence Three",
    location: "University District, Zone A",
    type: "Hostel",
    status: "Active",
    image: "/assets/image 3.png",
    occupancy: "92%",
    totalUnits: 50,
    roi: "12.5%",
    valuation: "$1.2M",
  }
];
