import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";
import HeaderMobile from "@/components/layout/HeaderMobile";
import MobileSidebar from "@/components/layout/MobileSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} antialiased`}
      >
        <div className="min-h-screen flex lg:pr-10 lg:pl-2.5 bg-[#F7F9FB]">
          {/* Sidebar */}
          <aside className="h-auto hidden lg:block pt-7.5 pl-7.5 pr-12.5">
            <Sidebar />
            <MobileSidebar/>
          </aside>

          {/* Main */}
          <div className="flex-1 flex flex-col">
            <Header />
            <HeaderMobile/>

            <main className="flex-1 overflow-y-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
